SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8  # seconds
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS: int = 20
PLAYER_TURN_SPEED: int = 300
PLAYER_SPEED: int = 200
PLAYER_SHOOT_SPEED: int = 500

SHOT_RADIUS: int = 5
PLAYER_SHOOT_COOLDOWN: float = 0.3
